### PR TITLE
Simulation

### PR DESCRIPTION
**Pull request by tongtybj**
Add the simulation mode in gazebo for all aerial robot, especially for transformable aerial robot.

### CODE REVIEW

**Comment by tongtybj** [comment]
I will not merge this before the outdoor experiment of hydrus3.
And I also need to complete the model description for hydrusx series and general multirotor.

**Comment by KahnShi** [comment]
@tongtybj  When I compiled this branch in a new PC with ROS kinectic, it comes error when compiling aerial_robot_base, error is
`/home/jsk/ros/aerial_catkin_ws/src/aerial_robot/aerial_robot_base/src/kf/baro_bias_plugin.cpp: In member function ‘virtual void kf_plugin::KalmanFilterBaroBias::initialize(ros::NodeHandle, std::__cxx11::string, int)’:
`

`
/home/jsk/ros/aerial_catkin_ws/src/aerial_robot/aerial_robot_base/src/kf/baro_bias_plugin.cpp:57:30: error: ‘baseInit’ was not declared in this scope
       baseInit(nh, suffix, id);
`
Other package except aerial_robot compiled successfully.
Wish it could give you any clue.

**Comment by tongtybj** [comment]
@KahnShi 
This error is the same as the compile result of travis. If you have time, please  check the log of [travis](https://travis-ci.org/tongtybj/aerial_robot/jobs/231742190).

The reason is the package of ``` kalman_filter```  form another repository is updated [recently](https://github.com/tongtybj/kalman_filter/commit/cd74b0488024561f6040985bd1fb4b0e90717341).
But branch ``` simulation ``` is still using the previous version. 


The other branch ``` outdoor ``` #30  is updated according to the present ``` kalman_filter ```.
I was waiting to validate the outdoor experiment next Monday and then merge the ``` outdoor ```. Subsequently, the branch ``` simulation ``` can be rebased on the updated branch ``` master ```.
However, it is seems that the conflict prevent your work. So I am going to merge the branch ``` outdoor ``` now, and rebase simulation.

**Comment by tongtybj** [comment]
@KahnShi 
I update this branch, and travis passes.
However, you have to do ```git rebase origin/simulation``` in your local ``` simulation ``` branch, and maybe there are some conflict  you have to fix.

**Comment by KahnShi** [comment]
@tongtybj 
Got it. Thank you for your work and directions.

**Pull request merged**
